#!/usr/bin/env bash
set -euo pipefail

read reponame repobase < <(echo $(gh repo view --json defaultBranchRef,name -q '.name, .defaultBranchRef.name'))

scanbranch="${1:-$repobase}"
git checkout "${scanbranch}"
git pull

gen-cov "${reponame}" || true # some tests might fail - we still want to run the scanner
sonar-scanner \
  -Dsonar.sources=. \
  -Dsonar.host.url=http://localhost:9000 \
  -Dsonar.branch.name="${repobase}" \
  -Dsonar.login="${SQ_LOGIN_TOKEN}"
